---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Style/HashSyntax:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Layout:
  Enabled: false
